# Nome da Aplicação
spring.application.name=forumhub

# 1. Conexão com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/forum-hub
spring.datasource.username=postgres
spring.datasource.password=Mctom470

# 2. Configurações do Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Configuração de Segurança (JWT)
# Aqui definimos a secret. O código abaixo tenta ler uma variável do Windows chamada JWT_SECRET,
# se não achar, usa '12345678' por padrão.
api.security.token.secret=${JWT_SECRET:12345678}

# Extra: Log de erros para ajudar no Debug
logging.level.org.springframework.security=DEBUG