# Nome da Aplica��o
spring.application.name=forumhub

# 1. Conex�o com PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/forum-hub
spring.datasource.username=postgres
spring.datasource.password=Mctom470

# 2. Configura��es do Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Configura��o de Seguran�a (JWT)
# Aqui definimos a secret. O c�digo abaixo tenta ler uma vari�vel do Windows chamada JWT_SECRET,
# se n�o achar, usa '12345678' por padr�o.
api.security.token.secret=${JWT_SECRET:12345678}

# Extra: Log de erros para ajudar no Debug
logging.level.org.springframework.security=DEBUG